"""
Blocket scraper — generated by Hermes agent.

Uses browser-harness http_get for fast HTTP scraping.
Blocket renders listings server-side, so pure HTML extraction works.

Test: python scrape.py --vendor blocket
"""

import re
import sys
import os
from urllib.parse import quote

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scrapers.base import ScrapeResult

# browser-harness
sys.path.insert(0, "/tmp/browser-harness")
from helpers import http_get

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    "Accept-Language": "sv-SE,sv;q=0.9,en;q=0.8",
}


def scrape(query: str, category: str) -> ScrapeResult:
    """Scrape Blocket search results for a query."""
    if category == "cars":
        url = f"https://www.blocket.se/mobility/search/car?q={quote(query)}"
    else:
        url = f"https://www.blocket.se/recommerce/forsale/search?category=0.93&q={quote(query)}"

    try:
        html = http_get(url, headers=HEADERS, timeout=15)
    except Exception as e:
        return ScrapeResult(
            items=[],
            errors=[f"http_get failed: {e}"],
            vendor="blocket",
            query=query,
        )

    if not html or len(html) < 5000:
        return ScrapeResult(
            items=[],
            errors=[f"empty/blocked response ({len(html) if html else 0} bytes)"],
            vendor="blocket",
            query=query,
        )

    items = []
    articles = re.findall(r'<article[^>]*>(.*?)</article>', html, re.DOTALL)

    for art in articles:
        link_m = re.search(r'href="(https://www\.blocket\.se/(?:recommerce/forsale|mobility)/item/\d+)"', art)
        title_m = re.search(r'<h2[^>]*>(.*?)</h2>', art, re.DOTALL)
        price_m = re.search(r'(\d[\d\s]*)\s*kr', art)

        if link_m and title_m:
            title = re.sub(r'<[^>]+>', '', title_m.group(1)).strip()
            price = int(price_m.group(1).replace(' ', '').replace('\xa0', '')) if price_m else None
            if title and price:
                items.append({
                    "title": title[:120],
                    "url": link_m.group(1),
                    "price": price,
                    "category": category,
                    "source": "blocket",
                })

    return ScrapeResult(items=items, vendor="blocket", query=query)
