"""
Tradera scraper — generated by Hermes agent.

Tradera renders listings client-side. This scraper uses browser-harness http_get
with regex fallback on SSR HTML. Limited results — browser-harness js() recommended
for full extraction.

Known issues:
- Save-search popup may block extraction (close with browser_click if using browser mode)
- Price elements use aria-describedby linking
- Some searches return 0 results with category filter

Test: python scrape.py --vendor tradera
"""

import re
import sys
import os
from urllib.parse import quote

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scrapers.base import ScrapeResult

sys.path.insert(0, "/tmp/browser-harness")
from helpers import http_get

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    "Accept-Language": "sv-SE,sv;q=0.9,en;q=0.8",
}


def scrape(query: str, category: str) -> ScrapeResult:
    """Scrape Tradera search results. Uses SSR HTML pattern matching."""
    url = f"https://www.tradera.com/search?q={quote(query)}"

    try:
        html = http_get(url, headers=HEADERS, timeout=15)
    except Exception as e:
        return ScrapeResult(
            items=[],
            errors=[f"http_get failed: {e}"],
            vendor="tradera",
            query=query,
        )

    if not html or len(html) < 5000:
        return ScrapeResult(
            items=[],
            errors=[f"empty response ({len(html) if html else 0} bytes)"],
            vendor="tradera",
            query=query,
        )

    items = []
    # Extract from SSR HTML — title+price from text blocks
    blocks = re.findall(
        r'(?:title|aria-label)="([^"]+)"[^>]*href="(/item/\d+/[^"]+)".*?(?:Pris:)\s*(\d[\d\s]*)\s*kr',
        html, re.DOTALL
    )

    seen = set()
    for title, path, price_str in blocks:
        full_url = f"https://www.tradera.com{path}"
        if full_url in seen:
            continue
        seen.add(full_url)
        try:
            price = int(price_str.replace(' ', '').replace('\xa0', ''))
        except ValueError:
            price = None

        items.append({
            "title": title[:120],
            "url": full_url,
            "price": price,
            "category": category,
            "source": "tradera",
        })

    if not items:
        return ScrapeResult(
            items=[],
            errors=[f"no items extracted — DOM may have changed (page: {len(html)} bytes)"],
            vendor="tradera",
            query=query,
        )

    return ScrapeResult(items=items, vendor="tradera", query=query)
